[phases.setup]
# FFmpeg e dependências para comandos de música
aptPkgs = [
    "ffmpeg",
    "libopus0",
    "libopus-dev",
    "libffi-dev",
    "libnacl-dev",
    "libsodium-dev",
    "python3-dev",
    "libssl-dev",
    "build-essential"
]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir PyNaCl --force-reinstall"
]

[start]
cmd = "python main.py"
